image: jelaniwoods/appdev2023-sinatra-template-test

tasks:
  - env:
      DATABASE_URL: "postgresql://gitpod@localhost"
    before: |
      echo 'export DATABASE_URL="postgresql://gitpod@localhost"' | sudo tee -a ~/.bashrc
      sudo cp -r /home/student /home/gitpod && sudo chmod 777 /home/gitpod
      bin/setup
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify
    - eamodio.gitlens
